### ISSUE TITLE
WriteSchema can deadlock

### ISSUE THREAD

**Issue by epaulson10** [authzed/spicedb#1485]
Hello,

I've recently discovered that `WriteSchema` has a potential deadlock, due to this PR that Authzed put up to the Rudd library: https://github.com/dalzilio/rudd/pull/1

That PR introduced recursive read locking on a `sync.RWMutex`, which is not supported. What happens is that the logic that is run when calling `WriteSchema` does a recursive read lock, and a GC finalizer does a write lock. If a GC happens in between a first RLock() and the second, recursive RLock(), the finalizer will call Lock(), and cause a deadlock: the second RLock() will never succeed, since the call to Lock() is preventing new RLocks() from occurring, and yet the first RLock() will never be unlocked.

The recursive lock occurs because [these functions that do operations on if a node is marked](https://github.com/dalzilio/rudd/blob/0a0cd32c7df9b9c8021d48764dbe411cec6eb96d/hudd.go#L46) are called from t[his function](https://github.com/dalzilio/rudd/blob/0a0cd32c7df9b9c8021d48764dbe411cec6eb96d/hudd.go#L243C18-L243C30), which also acquires a read lock.

I have a test harness that issues a lot of `WriteSchema` requests against a SpiceDB running in `serve-testing` mode, and this occurs quite frequently.

I have put a test up on my fork that shows the deadlock with WriteSchema is possible: https://github.com/epaulson10/spicedb/commit/18cd91c0e4e36233d02185abe84e2dc81cad9573. The test issues a bunch of `WriteSchema` calls against a locally running test server using one of your large example schemas, while hammering `runtime.GC()` in a goroutine to make the race condition happen more often. If you run it with a timeout, you should see the deadlock pretty quickly:

```sh
~/repos/spicedb/pkg/cmd/testserver on write-schema-deadlock-test
❯ go test -test.v -timeout 10s .
=== RUN   TestShowcaseDeadlockIntroducedInRuddLibrary
    testserver_test.go:76: On iteration 0
    testserver_test.go:76: On iteration 1
    testserver_test.go:76: On iteration 2
    testserver_test.go:76: On iteration 3
panic: test timed out after 10s
running tests:
        TestShowcaseDeadlockIntroducedInRuddLibrary (10s)

<Lots of irrelevant stack traces omitted>
...
goroutine 19 [sync.RWMutex.Lock]:
sync.runtime_SemacquireRWMutex(0x14000084508?, 0x84?, 0x14000244690?)
        /opt/homebrew/Cellar/go/1.20.7/libexec/src/runtime/sema.go:87 +0x28
sync.(*RWMutex).Lock(0x14000084558?)
        /opt/homebrew/Cellar/go/1.20.7/libexec/src/sync/rwmutex.go:152 +0xfc
github.com/dalzilio/rudd.New.func1(0x1400079c5d8)
        /Users/epaulson/go/pkg/mod/github.com/dalzilio/rudd@v1.1.1-0.20220422201445-0a0cd32c7df9/hudd.go:145 +0x48
...
goroutine 62 [sync.RWMutex.RLock]:
sync.runtime_SemacquireRWMutexR(0x14000878ef8?, 0xec?, 0x0?)
        /opt/homebrew/Cellar/go/1.20.7/libexec/src/runtime/sema.go:82 +0x28
sync.(*RWMutex).RLock(...)
        /opt/homebrew/Cellar/go/1.20.7/libexec/src/sync/rwmutex.go:71
github.com/dalzilio/rudd.(*tables).ismarked(0x140001bd770?, 0x7a?)
        /Users/epaulson/go/pkg/mod/github.com/dalzilio/rudd@v1.1.1-0.20220422201445-0a0cd32c7df9/hudd.go:47 +0x80
github.com/dalzilio/rudd.(*tables).allnodesfrom(0x140001bd770, 0x14000879060, {0x14000879158, 0x1, 0x14000879088?})
        /Users/epaulson/go/pkg/mod/github.com/dalzilio/rudd@v1.1.1-0.20220422201445-0a0cd32c7df9/hudd.go:258 +0x130
github.com/dalzilio/rudd.(*BDD).Allnodes(0x1400058d180, 0x1004aa624?, {0x14000879158?, 0x1, 0x1})
        /Users/epaulson/go/pkg/mod/github.com/dalzilio/rudd@v1.1.1-0.20220422201445-0a0cd32c7df9/operations.go:712 +0xc8
github.com/dalzilio/rudd.(*BDD).Print(0x101cc5da0?, {0x12ac54080, 0x1400047e8d0}, {0x14000879158?, 0x140008be660?, 0x0?})
        /Users/epaulson/go/pkg/mod/github.com/dalzilio/rudd@v1.1.1-0.20220422201445-0a0cd32c7df9/stdio.go:64 +0x158
github.com/authzed/spicedb/internal/namespace.computeCanonicalCacheKeys(0x14000588060, 0x14000070500?)
        /Users/epaulson/repos/spicedb/internal/namespace/canonicalization.go:89 +0x230
github.com/authzed/spicedb/internal/namespace.AnnotateNamespace(0x14000588060)
        /Users/epaulson/repos/spicedb/internal/namespace/annotate.go:11 +0x34
github.com/authzed/spicedb/internal/services/shared.ValidateSchemaChanges({0x101f88be0, 0x140007187e0}, 0x140000feaf0, 0x0)
        /Users/epaulson/repos/spicedb/internal/services/shared/schema.go:55 +0x334
github.com/authzed/spicedb/internal/services/v1.(*schemaServer).WriteSchema(0x140003982e8, {0x101f88be0?, 0x140007187e0}, 0x14000a59340)
        /Users/epaulson/repos/spicedb/internal/services/v1/schema.go:117 +0x16c
github.com/authzed/authzed-go/proto/authzed/api/v1._SchemaService_WriteSchema_Handler.func1({0x101f88be0, 0x140007187e0}, {0x101e6cd60?, 0x14000a59340})
        /Users/epaulson/go/pkg/mod/github.com/authzed/authzed-go@v0.9.0/proto/authzed/api/v1/schema_service_grpc.pb.go:135 +0x74
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x101f88be0, 0x140007186c0}, {0x101e6cd60, 0x14000a59340}, 0x12ae2dfe8?, 0x1400000c318)
        /Users/epaulson/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.5/interceptors/server.go:22 +0x1e0
github.com/authzed/spicedb/internal/middleware.ChainUnaryServer.func1.1.1({0x101f88be0?, 0x140007186c0?}, {0x101e6cd60?, 0x14000a59340?})
        /Users/epaulson/repos/spicedb/internal/middleware/chain.go:23 +0x3c
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/validator.UnaryServerInterceptor.func1({0x101f88be0, 0x140007186c0}, {0x101e6cd60, 0x14000a59340}, 0x1400056d638?, 0x1400059e0a0)
        /Users/epaulson/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.5/interceptors/validator/interceptors.go:23 +0x7c
github.com/authzed/spicedb/internal/middleware.ChainUnaryServer.func1.1.1({0x101f88be0?, 0x140007186c0?}, {0x101e6cd60?, 0x14000a59340?})
        /Users/epaulson/repos/spicedb/internal/middleware/chain.go:23 +0x3c
github.com/authzed/spicedb/internal/middleware.ChainUnaryServer.func1({0x101f88be0, 0x140007186c0}, {0x101e6cd60, 0x14000a59340}, 0x140007186c0?, 0x102e9b5e0?)
        /Users/epaulson/repos/spicedb/internal/middleware/chain.go:32 +0xb8
github.com/authzed/spicedb/internal/middleware/servicespecific.UnaryServerInterceptor({0x101f88be0, 0x140007186c0}, {0x101e6cd60, 0x14000a59340}, 0x1400059e080, 0x1400000c318)
        /Users/epaulson/repos/spicedb/internal/middleware/servicespecific/servicespecific.go:25 +0x84
google.golang.org/grpc.getChainUnaryHandler.func1({0x101f88be0, 0x140007186c0}, {0x101e6cd60, 0x14000a59340})
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1156 +0xa0
github.com/authzed/spicedb/internal/middleware/consistency.UnaryServerInterceptor.func1({0x101f88be0, 0x14000718660}, {0x101e6cd60?, 0x14000a59340}, 0x1400059e080, 0x14000514000)
        /Users/epaulson/repos/spicedb/internal/middleware/consistency/consistency.go:166 +0x1c8
google.golang.org/grpc.getChainUnaryHandler.func1({0x101f88be0, 0x14000718660}, {0x101e6cd60, 0x14000a59340})
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1156 +0xa0
github.com/authzed/spicedb/internal/middleware/dispatcher.UnaryServerInterceptor.func1({0x101f88be0, 0x140007184b0}, {0x101e6cd60, 0x14000a59340}, 0x1400059e080?, 0x14000a59a00)
        /Users/epaulson/repos/spicedb/internal/middleware/dispatcher/dispatcher.go:66 +0x104
google.golang.org/grpc.getChainUnaryHandler.func1({0x101f88be0, 0x140007184b0}, {0x101e6cd60, 0x14000a59340})
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1156 +0xa0
github.com/authzed/spicedb/internal/middleware/pertoken.(*MiddlewareForTesting).UnaryServerInterceptor.func1({0x101f88be0, 0x14000718390}, {0x101e6cd60, 0x14000a59340}, 0x1400059e080?, 0x14000a59380)
        /Users/epaulson/repos/spicedb/internal/middleware/pertoken/pertoken.go:83 +0x11c
google.golang.org/grpc.chainUnaryInterceptors.func1({0x101f88be0, 0x14000718390}, {0x101e6cd60, 0x14000a59340}, 0x1400056da38?, 0x100991058?)
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1147 +0x88
github.com/authzed/authzed-go/proto/authzed/api/v1._SchemaService_WriteSchema_Handler({0x101d871e0?, 0x140003982e8}, {0x101f88be0, 0x14000718390}, 0x140003e6230, 0x1400030abe0)
        /Users/epaulson/go/pkg/mod/github.com/authzed/authzed-go@v0.9.0/proto/authzed/api/v1/schema_service_grpc.pb.go:137 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0x14000025c20, {0x101f91720, 0x1400051a340}, 0x1400041c5a0, 0x140002d6930, 0x102e39818, 0x0)
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1337 +0xc90
google.golang.org/grpc.(*Server).handleStream(0x14000025c20, {0x101f91720, 0x1400051a340}, 0x1400041c5a0, 0x0)
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:1714 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:959 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/epaulson/go/pkg/mod/google.golang.org/grpc@v1.56.2/server.go:957 +0x16c

```

**Comment by ecordell** [comment]
@epaulson10 Nice work tracking this down! 

I opened up https://github.com/dalzilio/rudd/pull/2 to fix this. I tested with your reproducer and didn't see any deadlocks after making this change locally.
