### ISSUE TITLE
Ensure GitHub releases begin with `v`

### ISSUE THREAD

**Issue by ecordell** [authzed/spicedb#1782]
### What platforms are affected?

linux, macos, windows

### What architectures are affected?

amd64, arm64

### What SpiceDB version are you using?

v1.29.2

### Steps to Reproduce

1. Make a SpiceDB release with a tag without a `v` prefix
2. Run SpiceDB without the release check disabled

### Expected Result

Observe:
```
goroutine 1 [running]:
github.com/authzed/spicedb/pkg/cmd/server.DefaultPreRunE.CheckAndLogRunE.func6(0x14000b3b200?, {0x100683ffc?, 0x16?, 0x0?})
	/home/runner/actions-runner/_work/spicedb/spicedb/pkg/releases/cli.go:51 +0x108
github.com/authzed/spicedb/pkg/cmd/server.DefaultPreRunE.CommandStack.func8(0x14000b3d600?, {0x1049fb120, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/jzelinskie/cobrautil/v2@v2.0.0-20231016191810-9f8a4f6d038a/cobrautil.go:78 +0x78
github.com/spf13/cobra.(*Command).execute(0x14000b3b200, {0x1049fb120, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:968 +0x7e8
github.com/spf13/cobra.(*Command).ExecuteC(0x140003d3200)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/home/runner/actions-runner/_work/spicedb/spicedb/cmd/spicedb/main.go:81 +0x4c0
```

### Actual Result

Note that the underlying cause of the panic is fixed, but since we have other assumptions in the release process that the version begins with a `v`, we should validate this.

**Comment by nchepanov** [comment]
Why is this a default behavior?

I was just debugging some integration tests failing only to discover that a service failed to start `spicedb` because a new release of spicedb had a typo in the version name. I understand that there's a way to disable it, but I really question the value of this behavior being set by default for all users? It definitely caught me by surprise.

Have you considered changing the default behavior? I can only assume how many users were affected by this typo today.

**Comment by ecordell** [comment]
> Why is this a default behavior?

The goal is to provide information when the release you're running is out of date, since there may be important security updates in new versions (as there is in the latest release of SpiceDB!)

Note that this is supposed to fail gracefully and skip the check entirely if there is any issue with the GitHub API - the fact that it didn't is a bug (that is now fixed in head). This issue is just to follow up and make sure assumptions are always enforced by CD.

> Have you considered changing the default behavior? I can only assume how many users were affected by this typo today.

That's always a discussion to have, though this feature exists with the best of intentions. The good news is that this only happens on startup, so no stably-running SpiceDB instances were affected.
