### ISSUE TITLE
Panic (SIGSEGV) when writing schema

### ISSUE THREAD

**Issue by williamdclt** [authzed/spicedb#429]
## Summary

Updating my schema (using zed or the Schema API) results in a SIGSEGV, and therefore a panic. The schema is not updated.

## Details

I don't have the time to make a reproducible scenario right now, sorry. I am trying to change a relation from:

```
definition organisation {
	relation manager: user
	relation member: user
	permission user = manager + member

	relation flag_billing: user:*
}
```

To:

```
definition organisation {
	relation manager: user
	relation member: user
	permission user = manager + member

	relation flag_billing: organisation#user // <- the change
}
```

<summary>
I'm getting this error:
<details>

```
spicedb_1   | {"level":"info","module":"pgx","args":[],"pid":114,"rowCount":1,"sql":"SELECT MAX(id) FROM relation_tuple_transaction","time":0.3731,"time":"2022-02-28T19:07:59Z","message":"Query"}
spicedb_1   | panic: runtime error: invalid memory address or nil pointer dereference
spicedb_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xedc3e1]
spicedb_1   |
spicedb_1   | goroutine 110 [running]:
spicedb_1   | github.com/authzed/spicedb/internal/services/shared.SanityCheckExistingRelationships({0x16b38d8, 0xc000a26330}, {0x16d4608, 0xc0006854d0}, 0xc0006a88a0, {0xc0000481c0, 0x60})
spicedb_1   | 	/home/runner/work/spicedb/spicedb/internal/services/shared/schema.go:116 +0x841
spicedb_1   | github.com/authzed/spicedb/internal/services/v1.(*schemaServer).WriteSchema(0xc0004929c0, {0x16b38d8, 0xc000a26330}, 0xc000a1ac40)
spicedb_1   | 	/home/runner/work/spicedb/spicedb/internal/services/v1/schema.go:112 +0x48f
spicedb_1   | github.com/authzed/authzed-go/proto/authzed/api/v1._SchemaService_WriteSchema_Handler.func1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/authzed/authzed-go@v0.4.1/proto/authzed/api/v1/schema_service_grpc.pb.go:126 +0x78
spicedb_1   | github.com/grpc-ecosystem/go-grpc-middleware/validator.UnaryServerInterceptor.func1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40}, 0x3, 0xc000134990)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/validator/validator.go:47 +0x6f
spicedb_1   | github.com/authzed/spicedb/internal/middleware/servicespecific.UnaryServerInterceptor({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40}, 0xc000493ec0, 0xc000134990)
spicedb_1   | 	/home/runner/work/spicedb/spicedb/internal/middleware/servicespecific/servicespecific.go:25 +0x87
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1116 +0x5b
spicedb_1   | github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).UnaryServerInterceptor.func1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40}, 0x1, 0xc000a1ac80)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x87
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
spicedb_1   | github.com/grpc-ecosystem/go-grpc-middleware/auth.UnaryServerInterceptor.func1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40}, 0xc000493ec0, 0xc000a1ac80)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/auth/auth.go:47 +0xba
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a26330}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
spicedb_1   | go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x16b38d8, 0xc000a26240}, {0x12b82a0, 0xc000a1ac40}, 0xc000493ec0, 0xc000a1ac80)
spicedb_1   | 	/home/runner/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.28.0/interceptor.go:325 +0x61c
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a26240}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
spicedb_1   | github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x16b38d8, 0xc000a26210}, {0x12b82a0, 0xc000a1ac40}, 0x352f8a071, 0xc000a1ac80)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20210831071041-dd1540ef8252/interceptors/server.go:22 +0x2bd
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a26210}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
spicedb_1   | github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x16b38d8, 0xc000a26120}, {0x12b82a0, 0xc000a1ac40}, 0x352f82119, 0xc000a1ac80)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20210831071041-dd1540ef8252/interceptors/server.go:22 +0x2bd
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a26120}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
spicedb_1   | github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x16b38d8, 0xc000a05ec0}, {0x12b82a0, 0xc000a1ac40}, 0x12dd200, 0xc000a1ac80)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0-rc.2.0.20210831071041-dd1540ef8252/interceptors/server.go:22 +0x2bd
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1.1({0x16b38d8, 0xc000a05ec0}, {0x12b82a0, 0xc000a1ac40})
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1119 +0x83
spicedb_1   | google.golang.org/grpc.chainUnaryInterceptors.func1({0x16b38d8, 0xc000a05ec0}, {0x12b82a0, 0xc000a1ac40}, 0xc000493ec0, 0xc000134990)
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1121 +0x12b
spicedb_1   | github.com/authzed/authzed-go/proto/authzed/api/v1._SchemaService_WriteSchema_Handler({0x12699c0, 0xc0004929c0}, {0x16b38d8, 0xc000a05ec0}, 0xc000532ae0, 0xc0005723c0)
spicedb_1   | 	/home/runner/go/pkg/mod/github.com/authzed/authzed-go@v0.4.1/proto/authzed/api/v1/schema_service_grpc.pb.go:128 +0x138
spicedb_1   | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008e8000, {0x16cace0, 0xc0005a4000}, 0xc00027f440, 0xc000441590, 0x2087c18, 0x0)
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
spicedb_1   | google.golang.org/grpc.(*Server).handleStream(0xc0008e8000, {0x16cace0, 0xc0005a4000}, 0xc00027f440, 0x0)
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
spicedb_1   | google.golang.org/grpc.(*Server).serveStreams.func1.2()
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921 +0x98
spicedb_1   | created by google.golang.org/grpc.(*Server).serveStreams.func1
spicedb_1   | 	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:919 +0x294
spicedb-testing_spicedb_1 exited with code 2
```

</details>
</summary>

## Environment

This is my local machine (Macbook) on docker-compose. I am using the `quay.io/authzed/spicedb` docker image, v1.4.0 (latest at time of writing). I have a large amount of data loaded in database, although I don't think it matters.

**Comment by josephschorr** [comment]
@williamdclt What do you get back if you run that `SELECT` call in your database?

**Comment by williamdclt** [comment]
`60922`

**Comment by josephschorr** [comment]
Okay, I think I see the issue. Will issue a fix shortly.
