### ISSUE TITLE
SpiceDb crashing unexpectedly

### ISSUE THREAD

**Issue by jakub-lesniak-mck** [authzed/spicedb#850]
I came across a weird behaviour for SpiceDB - it crashed with an exit code 2.

Here is the tail of the log:
```
{"level":"error","module":"pgx","args":[],"err":"ERROR: relation \"relation_tuple_transaction\" does not exist (SQLSTATE 42P01)","pid":7266,"sql":"\n\tSELECT COALESCE(\n\t\t(SELECT MIN(id) FROM relation_tuple_transaction WHERE timestamp >= TO_TIMESTAMP(FLOOR(EXTRACT(EPOCH FROM NOW() AT TIME ZONE 'utc') * 1000000000 / 5000000000) * 5000000000 / 1000000000) AT TIME ZONE 'utc'),\n\t\t(SELECT MAX(id) FROM relation_tuple_transaction)\n\t),\n\t5000000000 - CAST(EXTRACT(EPOCH FROM NOW() AT TIME ZONE 'utc') * 1000000000 as bigint) % 5000000000;","time":"2022-09-28T11:52:42Z","message":"Query"}
panic: interface conversion: interface {} is nil, not decimal.Decimal

goroutine 786 [running]:
github.com/authzed/spicedb/internal/datastore/common/revisions.(*CachedOptimizedRevisions).OptimizedRevision(0xc000b087c0, {0x2117760?, 0xc000e74280?})
	/home/runner/work/spicedb/spicedb/internal/datastore/common/revisions/optimized.go:72 +0x4d3
github.com/authzed/spicedb/internal/datastore/proxy.hedgingProxy.OptimizedRevision.func1({0x2117760?, 0xc000e74280?}, 0x0?)
	/home/runner/work/spicedb/spicedb/internal/datastore/proxy/hedging.go:179 +0x65
created by github.com/authzed/spicedb/internal/datastore/proxy.newHedger.func1
	/home/runner/work/spicedb/spicedb/internal/datastore/proxy/hedging.go:78 +0x27b
paw-marketplace-spicedb-1 exited with code 2 
```

It is being run inside a docker-compose like so:

```
pg-spicedb:
    image: postgres:14-alpine
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d spicedb' ]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - 'traefik.enable=false'
    expose:
      - '5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: spicedb
    volumes:
      - pg-spicedb-data:/var/lib/postgresql/data
 
spicedb:
    image: quay.io/authzed/spicedb:v1.9.0
    depends_on:
      - pg-spicedb
    labels:
      - 'traefik.enable=false'
    ports:
      - 50051:50051
    volumes:
      - ./libs/authz/schema.local.yml:/schema.yml
    environment:
      - SPICEDB_GRPC_PRESHARED_KEY=localadmin
      - SPICEDB_GRPC_ENABLED=1
      - SPICEDB_GRPC_ADDR=:50051
      - SPICEDB_GRPC_NO_TLS=1
      - SPICEDB_METRICS_ENABLED=0
      - SPICEDB_DASHBOARD_ENABLED=0
      - SPICEDB_DATASTORE_ENGINE=postgres
      - SPICEDB_DATASTORE_CONN_URI=postgresql://postgres:postgres@pg-spicedb:5432/spicedb?sslmode=disable
      - SPICEDB_DATASTORE_BOOTSTRAP_FILES=/schema.yml
      - SPICEDB_DATASTORE_BOOTSTRAP_OVERWRITE=1
      - SPICEDB_TELEMETRY_ENDPOINT=
    command: serve

**Comment by vroldanbet** [comment]
👋🏻 It seems like you are running v1.9.0. In that version, if an error happened while checking for optimized revisions, it was not checked and would panic:

https://github.com/authzed/spicedb/blob/ae4552ed89f0561f71893da2feeb7feb1e767e71/internal/datastore/common/revisions/optimized.go#L71-L72

You can see that this was fixed in https://github.com/authzed/spicedb/pull/740, which is part of release `v1.12.0`.

Feel free to reopen if that does not fix your problem! 🙇🏻
